name: commanddelemiter
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  implicitly_animated_reorderable_list: ^0.2.1
  numberpicker: ^1.2.0
  flushbar: ^1.10.2
  shared_preferences: ^0.5.7+1
  get_it: ^4.0.2
  flutter_svg: ^0.17.4
  flutter_screenutil: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon_delimiter.png"
  image_path_android: "assets/icon_delimiter.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/skull.svg
#      languages
    - lang/ar.json
    - lang/en.json
    - lang/fa.json
    - lang/ru.json

  fonts:
    - family: Kill The Noise
      fonts:
        - asset: fonts/ljk_Kill_The_Noise/ljk_Kill_The_Noise.ttf
    - family: Foma_flibustier
      fonts:
        - asset: fonts/Foma_flibustier/Foma_flibustier.ttf
